//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDotNetCommunityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int articleid { get; set; }
        public string articletype { get; set; }
        public string articledesc { get; set; }
        public System.DateTime posteddate { get; set; }
        public Nullable<int> loginid { get; set; }
    
        public virtual userlogin userlogin { get; set; }
    }
}
