//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDotNetCommunityProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dotnetcommunitydbEntities : DbContext
    {
        public dotnetcommunitydbEntities()
            : base("name=dotnetcommunitydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adminlogin> adminlogins { get; set; }
        public DbSet<article> articles { get; set; }
        public DbSet<forumreply> forumreplies { get; set; }
        public DbSet<forum> forums { get; set; }
        public DbSet<project> projects { get; set; }
        public DbSet<userlogin> userlogins { get; set; }
    }
}
