//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDotNetCommunityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class forumreply
    {
        public int replyid { get; set; }
        public string reply { get; set; }
        public Nullable<int> questionid { get; set; }
        public Nullable<int> loginid { get; set; }
    
        public virtual userlogin userlogin { get; set; }
        public virtual forum forum { get; set; }
    }
}
